### ISSUE TITLE
exclude colors for a domain

### ISSUE THREAD

**Issue by lodgerz** [M-Reimer/togglewebsitecolors#3] opened 2018-01-02 13:03 UTC
hi,
can you add an options to exclude the edited colors for a specific domain (example nakedwoman.com :-))?
thanks.

**Comment by M-Reimer** [comment] 2018-08-18 11:23
I think this one is a duplicate of #6 which describes the potential solution better.

**Closed as completed by M-Reimer** 2018-08-18 11:23 UTC
